# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
plugins: [jekyll-paginate, redcarpet]

# Setup
title:            Yuxiang Zhu
tagline:          
description:      'A current master student in Nanjing University.'
url:              https://zzzzzyx.github.io/
baseurl:          /

author:
  name:           'Yuxiang Zhu'
  url:            https://zzzzzyx.github.io/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/zzzzzyx
